name: Label and organize abandoned PRs

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight
jobs:
  label-abandoned-pr:
    name: Tag abandoned PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write

    steps:
      - name: Check-out main repository
        uses: actions/checkout@v4

      - name: Label Stale/Abandoned
        run: python .github/bin/label_abandoned_prs.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: sh

      - name: Move PRs to correct project column
        run: python .github/bin/reorganize_board.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: sh
